---
# See more from https://gohugo.io/getting-started/configuration

# hostname (and path) to the root.
baseurl: "https://jianliu666.github.io/" 

# site title.
title: "Jian Blog" 

# See Module Config for how to import a theme.
theme: "hugo-theme-cleanwhite"

# A language tag as defined by RFC 5646. This value is used to populate:
#  - The <language> element in the internal RSS template
#  - The lang attribute of the <html> element in the internal alias template
languageCode: "en-us"

# google analytics tracking ID.
googleAnalytics: "" 

# the configuration option 'preserveTaxonomyNames' was removeed in Hugo 0.55.
preserveTaxonomyNames: true 

# default number of elements per page in pagination.
paginate: 10 

# if true, auto-detect Chinese/Japanese/Korean Languages in the content.
hasCJKLanguage: true 

# Hugo v0.20 introduced the ability to render your content to multiple output formats (e.g., to JSON, AMP html, or CSV). 
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true

# How to handle Markdown and other markup related configuration.
markup:
  tableOfContents:  # These settings only works for the Goldmark renderer:
    endLevel: 2     # The heading level, inclusive, to stop render the table of contents.
    startLevel: 1   # The heading level, values starting at 1 (h1), to start render the table of contents.
  highlight:        # Renders code with a syntax highlighter.
    style: dracula  # The CSS styles to apply to the highlighted code. 
  goldmark:
    renderer:
      unsafe: true  # By default, Goldmark does not render raw HTMLs and potentially dangerous links. If you have lots of inline HTML and/or JavaScript, you may need to turn this on.

params:
  header_image: img/banner.jpg
  SEOTitle: Jian Blog
  description: ""
  keyword: ""
  slogan: "一個人，可以走得很快；但一群人，可以走得很遠。"
  image_404: img/404-bg.jpg
  title_404: "你來到了沒有知識的荒原 :("
  page_view_conter: false
  # leancloud_app_id: ""
  # leancloud_app_key: ""
  # algolia_search: true
  # algolia_appId: ""
  # algolia_indexName: ""
  # algolia_apiKey: ""
  sidebar_about_description: "I'm a Backend Engineer working in Taipei, Taiwan."
  sidebar_avatar: "img/jian.jpg"
  featured_tags: false
  featured_condition_size: 5
  # ba_track_id: ""
  reward: false
  reward_guide: "嗯，這篇文章對我有用，鼓勵一下..."
  friends: false
  bookmarks: false
  about_me: true
  # giscus:
  #   data_repo: zhaohuabing/zhaohuabing.github.io
  #   data_repo_id: MDEwOlJlcG9zaXRvcnkxMzc3MjcyMjM=
  #   data_category: Announcements
  #   data_category_id: DIC_kwDOCDWM984CAWAt
  #   data_mapping: pathname
  #   data_reactions_enabled: '1'
  #   data_emit_metadata: '0'
  #   data_theme: light
  #   data_lang: en
  #   crossorigin: anonymous

  # We need a proxy to access Disqus api in China
  # disqus_proxy : 'https://disqusapi.zhaohuabing.com'
  # disqus_site : 'https://zhaohuabing.com'
  social:
    rss: true
    email: "jianliu0616@gmail.com"
    linkedin: "https://www.linkedin.com/in/jianliou/"
    github: "https://github.com/JianLiu666"
    # twitter: ""
    # wechat: ""
    # medium: ""
  # friend_link:
  #   - title: ""
  #     href: ""
  # bookmark_link:
  #   - title: ""
  #     href: ""
  # publications:
  #   title: MY BOOKS
  #   items:
  #     - title: ""
  #       image: "/img/yourimage.png"
  #       href: ""
  addtional_menus:
    - title: TECH
      href: /tech/
    - title: ARCHIVE
      href: /archive/
    - title: ABOUT
      href: /about/
  # algolia:
  #   vars:
  #     - title
  #     - summary
  #     - date
  #     - publishdate
  #     - expirydate
  #     - permalink
  #   params:
  #     - categories
  #     - tags
